name: Telemetry Vehicle Security Pipeline

# pipeline activated at each commit
on:
  push:
    branches: ["main", "job4-pipeline"]
  pull_request:
    branches: ["main", "job4-pipeline"]

permissions: 
  id-token: write   # for AWS OIDC work 
  contents: read    # to read the repository code
  packages: write   # necessary to push to ghcr

# disclaimer : job 2 and 3 run in parallel
jobs:
  # job 1: building images ALWAYS
  build:
    name: Build Applications
    runs-on: ubuntu-latest # VM Linux
    strategy:
      fail-fast: false # if a service fails, it doesn't cancell other building
      matrix:
        # services used to be identified by matrix
        service: [storage-service, watch-telemetry-svc]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # building the docker image
      - name: Build Docker Image
        run: |
          echo "Starting build for ${{ matrix.service }}..."
          
          # building dockerfile itself
          docker build -f src/${{ matrix.service }}/dockerfile -t ztv-${{ matrix.service }}:${{ github.sha }} .
          
      # saving image
      - name: Save Docker Image to Tar
        run: docker save ztv-${{ matrix.service }}:${{ github.sha }} > ${{ matrix.service }}-image.tar

      # upldoading image to actions
      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ matrix.service }}
          path: ${{ matrix.service }}-image.tar
          retention-days: 1 # it doesn't keep image for more than 1 day

  # job 2: scanning code with semgrep and c++check
  code_scan:
    name: SAST Scanning
    needs: build # depends on building stage (job 1)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      # SEMGREP scan (first step)
      - name: Semgrep Scan
        run: |
          python3 -m pip install semgrep
          semgrep scan --config "p/default" src/

      # CPPCheck (second stage)
      - name: Install Cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck
      - name: CPPCheck Scan
        # Check everything possible (performance, warns, errors etc...)
        # To not scan the whole lib (aws-sdk) code
        run: |
          echo "Starting scan with Cppcheck..."
          cppcheck --enable=all --suppress=missingIncludeSystem -i src/lib/ --error-exitcode=1 src/ -I src/common/include                             

  # job 3: scanning image with aquatrivysec and checking sbom
  image_scan:
    name: Image Scan and SBOM
    needs: build # also depends on job 1 (run in parallel with job 2)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # the same services from job 1
        service: [storage-service, watch-telemetry-svc]
    steps:
      # bringing repo from outside (job 1)
      - name: Checkout Repository
        uses: actions/checkout@v4

      # downloading .tar from job 1
      - name: Download Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image-${{ matrix.service }}

      # loading docker image from tar downloaded
      - name: Load Docker Image
        run: docker load < ${{ matrix.service }}-image.tar

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ztv-${{ matrix.service }}:${{ github.sha }}'
          format: 'table'
          # return 1 if it finds vulnerabilities because if pipeline fails (code 1)
          exit-code: '1'
          # focus on fixed problems
          ignore-unfixed: 'true'
          vuln-type: 'os,library'
          # it doesn't allow code to have high and critical problems
          severity: 'HIGH,CRITICAL'

  # job 4: final tests and IaC scan
  test_and_scan:
    name: Test, Push & Scan IaC
    needs: [code_scan, image_scan]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [storage-service, watch-telemetry-svc]
    steps:
      - uses: actions/checkout@v4

      # configuring AWS credential to tests
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      
      # building images on artifacts
      - name: Download built images
        uses: actions/download-artifact@v4
        with:
          name: docker-image-${{ matrix.service }}
          path: /tmp/images/ # Local garantido de download
        
      # loading those images
      - name: Load images
        run: docker load -i /tmp/images/${{ matrix.service }}-image.tar
  
      # testing storage service
      - name: Test storage-service 
        if: matrix.service == 'storage-service'
        env:
          QUEUE_URL: ${{ secrets.QUEUE_URL }}
        run: chmod +x scripts/test_storage_service.sh && ./scripts/test_storage_service.sh

      # testing watch telemetry service
      - name: Test watch-telemetry-svc
        if: matrix.service == 'watch-telemetry-svc'
        run: chmod +x scripts/test_watch_telemetry.sh && ./scripts/test_watch_telemetry.sh

      # logging on github container registry (to post the image)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # pushing image to the repo (posting it)
      - name: Push images to container registry
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker tag ztv-${{ matrix.service }}:${{ github.sha }} ghcr.io/$REPO_OWNER/${{ matrix.service }}:${{ github.sha }}
          docker push ghcr.io/$REPO_OWNER/${{ matrix.service }}:${{ github.sha }}

      # static scan of terraform files
      - name: Terrascan (IaC static scan)
        run: terrascan scan -d terraform/

      # dynamic scan of terraform infrastructure
      - name: Terratest (IaC dynamic test)
        run: |
          cd tests/terratest
          go test ./... -timeout 30m

  # job 5: release to AWS
  release:
    name: Release to AWS
    needs: [test_and_scan] # it depends on job 2 and 3, to scan code and image
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Terraform plan/apply
        run: |
          cd terraform
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

      - name: Deploy image (binary) to Lambda
        run: |
          echo "TODO: not tested yet"